import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-primaryBackground flex justify-center items-center lg:h-screen relative`}
      >
        {children}
        <div className="max-lg:hidden circlePosition w-[300px] h-[300px] bg-circleBackground rounded-[100%] absolute z-1 bottom-[-100px] left-[-100px] blur-[90px]"></div>
      </body>
    </html>
  );
}
